### ISSUE TITLE
8.x - Uncaught ReferenceError: Drupal is not defined at cse.results.js?v=1.x:40

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa_bar#17]

**Comment by adamdelaney** [comment]
Can you provide more context on where you are seeing this error?

**Comment by richardbporter** [comment]
![image](https://user-images.githubusercontent.com/1068523/35694387-d1172ccc-0746-11e8-88f0-334baab630ac.png)

**Comment by adamdelaney** [comment]
This is an issue because the cse.results.js is included as part of the uiowa_bar library and is included on every page in uiowa_bar_page_attachments(). We should look at scoping the behavior of cse.results.js behavior to only execute on the results page callback.
