### ISSUE TITLE
Remove API functions

### ISSUE THREAD

**Issue by brandonneil** [uiowa/uiowa_bar#2]
Should https://github.com/uiowa/uiowa_bar/blob/7.x-2.x/uiowa_bar.api.php be removed since altering the bar for custom divisional settings is no longer allowed?

**Comment by richardbporter** [comment]
That was just the documentation - the actual alter is at: https://github.com/uiowa/uiowa_bar/blob/1abae59c520b7551cbf829d9d08c8328a0e91115/includes/uiowa_bar.build.inc#L66
