### ISSUE TITLE
Remove custom links

### ISSUE THREAD

**Issue by dhannad** [uiowa/uiowa_bar#21]
When moving this to D8, we may want to consider dropping the custom links. Less than 2.5% of the sites use the links, and only 2 sites use both. [Arts](https://arts.uiowa.edu) probably has the most legitimate use, other than the sites who link to their office or college.

**Comment by adamdelaney** [comment]
I don't think is a usability thing it was more of a political thing, so my vote is keep it.

**Comment by bspeare** [comment]
CLAS uses these links on all of our sites.  Please keep them.

**Comment by adamdelaney** [comment]
Closing this issue for now.
