### ISSUE TITLE
D8 implement bootstrap 4 markup

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/uiowa_bar#26]
It has been decided that our base theme in d8 will be based on bootstrap 4 so we should leverage it's grid, form and positioning components.

**Comment by markahrens** [comment]
I agree, if we keep just the basic bar across the top. The functionality and features of the uiowa_bar are being discussed, so there may be some functionality that would cause us to change this. An example would be if it is a taller bar when loading the page and then having it get smaller as you scroll down the page.

**Comment by adamdelaney** [comment]
Who's apart of those discussions? Is this a d8 thing only or will these presentational changes be backported to d7 installs?

**Comment by markahrens** [comment]
> Who's apart of those discussions?

TBD, however we were planning to have this be part of the discussion at the meeting on Monday

> Is this a d8 thing only or will these presentational changes be backported to d7 installs?

TBD as well, it will likely depend on how dramatic the changes are and the effort to implement a backport.
