### ISSUE TITLE
8.x - Consider framework agnostic css

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa_bar#36]
It sounds like other groups on campus may want to use uiowa_bar but not bootstrap. We could take it a step further and pull a component into the module.

**Comment by joewhitsitt** [comment]
Blocked. Waiting to hear finalized plans regarding the future of the uiowa_bar. Looks like a pretty big departure which will require a rewrite and possibly integration with a non-bootstrap design system.

**Comment by richardbporter** [comment]
This is being handled at the theme level.
