### ISSUE TITLE
8.x - Use blocks for bar components

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa_bar#50]
Currently, the uiowa bar is rendered by hijacking the "top" section of the page layout. If current designs are any indication, we will need to switch to using blocks for each component with default placement of the blocks set by themes. This will allow us to be able to achieve placing the search box either in the uiowa bar or alongside the site name in the case of a department site.

**Comment by joewhitsitt** [comment]
this is in the back log for hp-project and I see it as a departure from uiowa_bar into more of a uiowa_header or just part of the base theme.

**Comment by pyrello** [comment]
An update: I think the future of the uiowa_bar module is that it eventually gets deprecated in favor of a new module called uiowa_search (currently embedded in the uiowa/uiowa project). The new module just provides the search form and search settings. The form is actually implemented by the uids_base theme. The remaining elements are just incorporated into the theme.

So, I think this issue is no longer relevant.
