### ISSUE TITLE
Line up lower edge of search field and button

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa_bar#54]
The lower edge of the search button is higher than the search field. See attached screenshot. 

![image](https://user-images.githubusercontent.com/52135878/78389699-cc412b80-75a8-11ea-8295-57f501b111c8.png)
Changing height for the button from 22px to 25px to match the input field fixes it.

**Comment by joewhitsitt** [comment]
The vanilla uiowa_bar should be good, but many sites (i am guilty of this) have overridden the uiowa_bar css to work with their font selections, etc.

Tippie has a whole bunch of overrides in their theme _page.scss starting at line 34 (#ui-wrapper) including padding for `#uiowa-bar #uiowa-search .form-control, #uiowa-bar #uiowa-search #edit-search-terms`

See for example a theme that hasn't done any overrides (bartik):
<img width="2230" alt="Screen Shot 2020-04-07 at 2 15 55 PM" src="https://user-images.githubusercontent.com/4663676/78710087-602d3300-78da-11ea-9e73-b0de849a70b2.png">

Closing.
